<section class="about container">
    <h2>Qu'est-ce que le test RIASEC ?</h2>
    <section class="origins">
        <h3>Les origines du test</h3>
        <img src="img/john_holland.jpg" alt="Portrait de John Holland, créateur du test RIASEC">
        <p>Le profil RIASEC est un modèle théorique élaboré par le psychologue et chercheur américain John Holland dans les années 70.<p>
        <p>L'acronyme résume les 6 types de personnalité définis par Holland. Le type Réaliste aime gérer les choses tangibles et aiment en général bricoler. Le type Investigateur préfère se poser des questions et aborder les choses selon une problématique. Le type Artistique adore créer et s'exprimer aux travers de médium. Le type Social aime gérer les gens, il est communicatif. Enfin le type Entreprenant n'aime pas se poser des questions il aime agir.</p>
        <p>Selon Holland le choix d'une profession, d'un métier, est une forme d'expression de la
        personnalité. L'appartenance d'un individu à l'un ou l'autre des six types est déterminée
        par ses habiletés, ses intérêts et certains traits de sa personnalité.
        Chaque profession implique un ensemble d'aptitudes et de postures correspondants à chacun
        des profils dans des mesures différentes. Holland a ainsi pu dresser une carte du monde
        professionnel qui permet à chacun de découvrir pour quels métiers il est fait.</p>
    </section>
    <section class="theorie">
        <h3>La théorie vocationnelle des métiers</h3>
        <p>Selon HOLLAND, les personnes d’un même « type » exercent souvent le même genre de travail, parce qu’ils s’apparentent par leur personnalité, parce qu’ils poursuivent des objectifs semblables, parce qu’ils présentent les mêmes dispositions physiques et psychologiques à l’égard de leur travail. La typologie d’une personne est établie en mesurant son degré d’affinité avec chacun des 6 types de manière à la classer par ordre d’importance, du type le plus marqué au type le moins marqué. Chez la plupart des gens, ce sont surtout les deux ou trois premiers types de leur hiérarchie personnelle qui ont une influence significative sur leur manière d’être et d’agir, tant dans leur
        vie personnelle que professionnelle.</p>
        <p>Ce modèle est donc d'un intérêt particulier, car à défaut d'autres modèles existants il ne définit pas exactement la personnalité, mais plutôt la vocation. Il vise à déterminer quelles sont les intérêts professionnels de l'individu et augmente la congruence de certains métiers avec le profil auquel il correspond.</p>
        <p>En résumé, il permet simplement et efficacement de trouver le métier dans lequel l'individu va être extrêmement motivé et épanoui. Aujourd'hui cette typologie est devenue une référence mondiale dans le milieu de l'orientation professionnelle.</p>
        
    </section>
    <section class="summaries">
        <h3>Les différents profils en quelques mots</h3>
        <article>
            <h4>Le REALISTE ou manuel</h4>
            <img src="img/metiers/realiste.jpg" alt="Ouvrier du bâtiment perché sur une architecture d'immeuble">
            <p>Les personnes de type « Réaliste » sont stables, tenaces, entières et robustes. Elles préfèrent les univers très tournés vers les choses pratiques et mettant en Jeu des produits bien définis. Elles aiment apprendre et travailler avec des machines et du matériel. Elles préfèrent les méthodes traditionnelles pour faire les choses. Elles aiment la vie à l’extérieur et peuvent préférer s’installer hors des villes.
            Les personnes de type « Réaliste » sont des réalisatrices et préfèrent l’action à la discussion.</p>
        </article>
        <article>
            <h4>L'INVESTIGATEUR ou scientifique</h4>
            <img src="img/metiers/investigateur.jpg" alt="Chercheuse observant son microscope">
            <p>Les personnes de type « Investigateur » cherchent à utiliser leurs aptitudes analytiques ou théoriques pour résoudre les problèmes. Le succès se matérialise pour elles de deux façons différentes : au plan académique par des diplômes et des études poussées et au plan professionnel par des découvertes, des publications et le respect que leur témoignent leurs collègues et pairs. La puissance, le conformisme et l’autorité les attirent peu. Elles considèrent l’argent seulement comme un moyen et non comme un but.</p>
        </article>
        <article>
            <h4>L'ARTISTE ou créatif</h4>
            <img src="img/metiers/artiste.jpg" alt="Sculpteur en pleine création">
            <p>Les personnes de type « Artiste » sont créatives, intuitives, expressives et spontanées. Elles apprécient les tâches où elles peuvent utiliser leurs aptitudes visuelles et verbales. Elles aiment travailler plutôt seules, mais n’aiment pas être ignorées. Elles aiment retenir l’attention des autres et être reconnues pour leurs apports créatifs. Les personnes de type « Artiste » aiment la liberté et la spontanéité. Elles se sentent parfois étouffées lorsqu’elles se trouvent dans un environnement trop structuré préfèrent travailler sur un projet de façon intense sans horaires ou organisation fixes.</p>
        </article>
        <article>
            <h4>Le SOCIAL ou altruiste</h4>
            <img src="img/metiers/social.jpg" alt="Travailleuse sociale conseillant une personne">
            <p>Les personnes de type « Social » cherchent à utiliser leurs aptitudes dans les relations interpersonnelles pour réduire les conflits et aider les autres à travailler ensemble pour le bien de tous. Pour ce type de personnes le succès se mesure en termes de valeur morale et humaniste. Les relations qu’elles établissent avec les autres et l’aide qu’elles peuvent apporter aux moins chanceux sont, à leurs yeux, importantes. Le succès n’est pas aussi primordial pour elles que la possibilité qu’elles ont d’agir avec les autres. Elles peuvent sacrifier leurs propres besoins et objectifs si elles pensent qu’un groupe en bénéficiera.</p>
        </article>
        <article>
            <h4>L' ENTREPRENANT ou leader</h4>
            <img src="img/metiers/entreprenant.jpg" alt="Chef d'entreprise à son bureau">
            <p>Les personnes de type « Entreprenant » sont énergiques, ambitieuses et rapides. Elles apprécient le pouvoir, le statut social et la richesse. Elles peuvent être très sûres d’elles-mêmes et persuasives. Elles sont prêtes à prendre des décisions et à les mettre en application. Elles passent rapidement à l’action, aiment les défis, le risque, l’aventure et la concurrence. En général, elles n’aiment pas la précision et le travail de détail. Elles passent habituellement peu de temps à fouiller un problème et préfèrent une analyse très rapide suivie d’action.</p>
        </article>
        <article>
            <h4>Le CONVENTIONNEL ou méthodique</h4>
            <img src="img/metiers/conventionnel.jpg" alt="Secrétaire à son ordinateur">
            <p>Les personnes de type « Conventionnel » sont consciencieuses, stables, régulières et précise. Elles excellent dans les tâches d’entretien ou de suivi. Elles ont tendance à préférer les méthodes sûres et éprouvées. Elles aiment les univers concrets, logiques, pratiques et dans lesquels les procédures et règles sont bien définies. Elles préfèrent travailler dans des bureaux où les horaires sont précis, où la formation est bonne et les avantages sociaux sûrs. Les personnes de type « Conventionnel » aiment savoir exactement ce qu’on attend d’elles, préfèrent des règles très précises qu’elles peuvent suivre avec un minimum de changement ou de dérangement.</p>
        </article>
    </section>
    <a href="questions1-interest.php" class="test_btn btn_link btn_bottom">Passer le test</a>
</section>
