<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/0ac17cb549.js"></script>
    <title>RIASEC : Test complet en ligne </title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
    <header id="top">
        <div>
            <img src="img/logo/logo_riasec.png" alt="logo Riasec">
            <img src="img/logo/logo_pro_emploi.png" alt="logo Pro Emploi">
        </div>
        <section>
            <h1>R I A S E C</h1>
            <p>Vos aptitudes et compétences personnelles</p>
        </section>
    </header>
    <main>
        <?php 
            include($template);
        ?>
    </main>
    <footer>
        <a href="#top"><i class="fas fa-chevron-up fa-2x"></i></a>
        <p>&copy;2019 Designed by Virginie Bouvarel</p>
    </footer>
    <script type="text/javascript" src="js/utils.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
</body>
</html>