<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/0ac17cb549.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="../css/normalize.css">
    <link rel="stylesheet" type="text/css" href="../css/admin.css">
    <title>Riasec Dashboard</title>
</head>

<body>
    <header class="flex">
        <h1><i class="fas fa-mug-hot"></i>DASHBOARD</h1>
        <a href="../index.php"><i class="fas fa-home"></i></a>
    </header>
    <main class="flex">
        <nav class="side-bar">
            <h3>TABLES</h3>
            <a href="majorList.php">DOMINANTES</a>
            <a href="minorList.php">MINEURES</a>
            <a href="professionsList.php">PROFESSIONS</a>
            <a href="questionsList.php">QUESTIONS</a>
        </nav>

        <section class="container">

            <?php
                // Contenu de la page
                include($template);
            ?>

        </section>

    </main>
</body>
</html>   
