<!-- Formulaire d'ajout d'une profession-->

<section class = "formAdmin">

    <h2>Modifier une profession</h2>

    <form method="post" action="professionsUpdate.php">
        <div>
            <label for="code">Code:</label>
            <input type="text" name="code" id="code" value="<?= $job["minor_code"];?>">
        </div>
        <div>
            <label for="name">Nom:</label>
            <input type="text" name="name" id="name" value="<?= $job["name"];?>">
        </div>
        <input type="hidden" name="id" value="<?= $job["id"]; ?>">
        <button type="submit" class="submit-button">Modifier la profession</button>
    </form>
</section>