<!-- Formulaire d'ajout d'une profession-->

<section class = "formAdmin">

    <h2>Ajouter une profession</h2>

    <form method="post" action="professionsAdd.php">
    <div>
            <label for="code">Code de la mineure :</label>
            <select id="code" name="code">
                <?php foreach($minorCodes as $minorCode): ?>
                    <option><?= $minorCode["code"]; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="name">Nom:</label>
            <input type="text" name="name" id="name">
        </div>
        <button type="submit" class="submit-button">Ajouter la profession</button>
    </form>
</section>