<!-- Formulaire d'ajout d'une mineure-->

<section class = "formAdmin">

    <h2>Modifier une mineure</h2>

    <form method="post" action="minorUpdate.php">
        <div>
            <label for="code">Code:</label>
            <input type="text" name="code" id="code" value="<?= $minor["code"];?>">
        </div>
        <div>
            <label for="name">Nom:</label>
            <input type="text" name="name" id="name" value="<?= $minor["name"];?>">
        </div>
        <div>
            <label for="description">Description:</label>
            <textarea id="description" name="description" rows="5" cols="75"><?= $minor["description"]; ?></textarea>
        </div>
        <input type="hidden" name="id" value="<?= $minor["id"]; ?>">
        <button type="submit" class="submit-button">Modifier la mineure</button>
    </form>
</section>