<!-- Formulaire d'ajout d'une mineure-->

<section class = "formAdmin">

    <h2>Ajouter une mineure</h2>

    <form method="post" action="minorAdd.php">
        <div>
            <label for="code">Code:</label>
            <input type="text" name="code" id="code">
        </div>
        <div>
            <label for="name">Name:</label>
            <input type="text" name="name" id="name">
        </div>
        <div>
            <label for="description">Description:</label>
            <textarea id="description" name="description" rows="5" cols="75"></textarea>
        </div>
        <button type="submit" class="submit-button">Ajouter la mineure</button>
    </form>
</section>