<!-- Formulaire d'ajout d'une question-->

<section class = "formAdmin">

    <h2>Ajouter une question</h2>


    <form method="post" action="questionsAdd.php">
        <div>
            <label for="number">Numéro:</label>
            <input type="text" name="number" id="number">
        </div>
        <div>
            <label for="type">Type:</label>
            <input type="text" name="type" id="type">
        </div>
        <div>
            <label for="class">Classe:</label>
            <input type="text" name="class" id="class">
        </div>
        <div>
            <label for="question">Question:</label>
            <input type="text" name="question" id="question">
        </div>

        <button type="submit" class="submit-button">Ajouter la question</button>
    </form>
</section>